spring.application.name=tuition-management-system

spring.application.name=tuition-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/tuition_db
spring.datasource.username=root
spring.datasource.password=imanya@123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true