# Replace with your actual database name, username, and password
spring.datasource.url=jdbc:mysql://localhost:3306/tuition_db
spring.datasource.username=root
spring.datasource.password=2downNDKay#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keeps your existing schema untouched and prints SQL queries for debugging
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081